version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    ignore:
      - dependency-name: 'mkdirp'
      - dependency-name: 'pirates'
      - dependency-name: 'minimatch'
      - dependency-name: 'slash'
      - dependency-name: 'ts-node'
      - dependency-name: 'which'
      - dependency-name: 'regenerator-runtime'
      - dependency-name: 'is-builtin-module'      
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: 'daily'
